root: true

parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  es6: true
  node: true

plugins:
  - import
  - prettier

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - xo
  - prettier

rules:
  eqeqeq: off
  no-eq-null: off
  no-negated-condition: off
  no-unused-vars:
  - error
  - vars: all
    args: after-used
    argsIgnorePattern: "^_"
    varsIgnorePattern: "^React$"
  import/no-extraneous-dependencies: error
  prettier/prettier: error
  no-console: 0
  react/prop-types: 0
  react/display-name: 0

settings:
  react: 
    version: 16.3.2

overrides:
  -
    files:
      - "**/test/**/*.js"
      - "**/*.test.js"
    env:
      jest: true
  -
    files:
      - "examples/**/*.js"
    env:
      browser: true
  -
    files:
      - "docs/**/*.js"
      - "examples/**/*.js"
    rules:
      import/no-unresolved: off
      import/no-extraneous-dependencies: off
